name: Greetings

on:
- pull_request_target
- issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome in and thank you for your contribution.\nUsually issues are responded to within 48 hours, but depending on the current workload that may be slightly longer.\n\nYou can also find us on slack at [idrinth-api-bench](https://join.slack.com/t/idrinth-api-bench/shared_invite/zt-2f4zmw2sz-c3etHzCFq3LtZpkR15xXMA)."
        pr-message: "Thank you for contributing!\nPlease make sure the actions pass. Once your pull request has been merged, you will automatically be added to the contributor's list on the website.\nIf you want to be shouted out on Linkedin, have a look for the [shoutout issue](https://github.com/Idrinth/api-bench/labels/shoutout) of the specific version.\n\nYou can also find us on slack at [idrinth-api-bench](https://join.slack.com/t/idrinth-api-bench/shared_invite/zt-2f4zmw2sz-c3etHzCFq3LtZpkR15xXMA)."
