name: Documentation Website STYLELINT
on:
  push:
    branches:
    - the-one
    paths:
      - '**.scss'
      - 'package-lock.json'
      - '.github/workflows/stylelint.yml'
  pull_request:
    branches:
    - the-one
    paths:
    - '**.scss'
    - 'package-lock.json'
    - '.github/workflows/stylelint.yml'
jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - run: npm run lint-styles
  duplicate-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - run: npm run lint-css
