name: TEST
on:
  push:
    branches:
    - the-one
    paths:
    - '**.ts'
    - '**.js'
    - '**.tsx'
    - '**.json'
    - '.github/workflows/test.yml'
  pull_request:
    branches:
    - the-one
    paths:
    - '**.ts'
    - '**.js'
    - '**.tsx'
    - '**.json'
    - '.github/workflows/test.yml'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - 20
        - 21
        - 22
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.version}}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{matrix.version}}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - run: npm run language
      - run: npm run contributors
      - run: npm run test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: unit-test-${{ env.CURRENT_NODE_VERSION }}
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part:
          - 0
          - 1
          - 2
          - 3
          - 4
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - run: npm run build
      - run: npm run e2e
        env:
          SPLIT: 5
          SPLIT_INDEX: ${{ matrix.part }}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: integration-${{ env.CURRENT_NODE_VERSION }}
  end:
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - integration
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
